DATASETS:
    TEST: ("cityscapes_fine_sem_seg_val",)

## test setting for cityscapes
INPUT:
    MIN_SIZE_TEST: 1024
    MAX_SIZE_TEST: 2048
    SIZE_DIVISIBILITY: -1
    FORMAT: "RGB"
TEST:
    EVAL_PERIOD: 2000
    AUG:
        ENABLED: True
        MIN_SIZES: [512, 768, 1024, 1280, 1536, 1792]
        MAX_SIZE: 4096
        FLIP: True